/*
 * File: app/view/AutoNav.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('sion.demo.view.AutoNav', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.autonav',

    itemId: 'AutoNav',
    width: 200,
    layout: 'accordion',
    title: '',

    initComponent: function() {
        var me = this;

        me.processAutoNav(me);
        me.callParent(arguments);
    },

    processAutoNav: function(config) {
        Ext.define(config.getNamespace()+'.store.AutoMenuStore', {
            extend: 'Ext.data.Store',

            requires: [
                'Ext.data.proxy.Ajax',
                'Ext.data.reader.Json',
                'Ext.data.Field'
            ],

            constructor: function(cfg) {
                var me = this;
                cfg = cfg || {};
                me.callParent([Ext.apply({
                    autoLoad: true,
                    storeId: 'AutoMenuStore',
                    data: [
                        {
                            title: 'Extjs学习',
                            iconCls: 's_icon_org_group',
                            menuItems: [
                                {
                                    text: '简单增删改查',
                                    iconCls: 's_icon_action_copy',
                                    viewName: 'User'
                                }
                            ]
                        },
                        {
                            title: 'mongo学习',
                            iconCls: 's_icon_money_yen',
                            menuItems: [
                                {
                                    text: '企业信息',
                                    iconCls: 's_icon_item_book',
                                    viewName: 'ComInfo'
                                },
                                {
                                    text: '重点企业',
                                    iconCls: 's_icon_file_star',
                                    viewName: 'PointCom'
                                },
                                {
                                    text: '未审批企业',
                                    iconCls: 's_icon_file_edit',
                                    viewName: 'ComWait'
                                },
                                {
                                    text: '未通过企业',
                                    iconCls: 's_icon_file_error',
                                    viewName: 'ComNoPass'
                                }
                            ]
                        }

                    ],
                    proxy: {
                        type: 'ajax',
                        reader: {
                            type: 'json'
                        }
                    },
                    fields: [
                        {
                            name: 'title'
                        },
                        {
                            name: 'iconCls'
                        },
                        {
                            name: 'menuItems'
                        }
                    ]
                }, cfg)]);
            }
        });


        var me = config,
            menus = [],
            myStore = Ext.create(me.getNamespace()+'.store.AutoMenuStore');
        myStore.each(function(obj) {
            var menu = {
                xtype:'menu',
                title:obj.get('title'),
                floating: false,
                iconCls:obj.get('iconCls')
            };
            var menuItems = [];
            obj.get('menuItems').forEach(function(element, index, array){
                var viewName = element.viewName;
                var path = me.getNamespace();
                var menuItem = Ext.create('Ext.menu.Item', {
                    text: element.text,
                    iconCls: element.iconCls,
                    listeners:{
                        click: {
                            fn: function (){
                                var tabs = Ext.ComponentQuery.query('#MyTabPanel')[0];
                                var className = me.getNamespace()+'.view.'+viewName;
                                var P1 = Ext.ComponentQuery.query('#'+viewName)[0];
                                if(!P1){
                                    P1 = Ext.create(className);
                                    P1.iconCls = element.iconCls;
                                    P1.title= element.text;
                                    P1.closable = true;
                                    P1.itemId = viewName;
                                    //tabs.remove(P1);
                                    tabs.add(P1);
                                }
                                tabs.setActiveTab(P1);

                            },
                            scope: me
                        }
                    }
                });
                menuItems.push(menuItem);
            });
            menu.items = menuItems;
            menus.push(menu);
        });
        me.items = menus;
        //         me.doLayout();
    }

});