/*
 * File: app/view/EmployEdit.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('sion.demo.view.EmployEdit', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.form.Panel',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.form.field.Number',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio'
    ],

    height: 273,
    width: 410,
    title: '信息编辑',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    height: 208,
                    bodyPadding: 10,
                    title: '',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    iconCls: '',
                                    text: '保存',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonClick,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        }
                    ],
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            hidden: true,
                            fieldLabel: 'Label',
                            name: 'id'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: '姓名',
                            name: 'name'
                        },
                        {
                            xtype: 'numberfield',
                            anchor: '100%',
                            fieldLabel: '年龄',
                            name: 'age'
                        },
                        {
                            xtype: 'radiogroup',
                            fieldLabel: '性别',
                            items: [
                                {
                                    xtype: 'radiofield',
                                    name: 'sex',
                                    boxLabel: '男',
                                    checked: true,
                                    inputValue: '男'
                                },
                                {
                                    xtype: 'radiofield',
                                    name: 'sex',
                                    boxLabel: '女',
                                    inputValue: '女'
                                }
                            ]
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: '邮箱',
                            name: 'email'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: '住址',
                            name: 'address'
                        }
                    ]
                }
            ],
            listeners: {
                beforerender: {
                    fn: me.onWindowBeforeRender,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, eOpts) {
        var me = this,
            form = me.down('form'),
            emp = form.getRecord();
        form.updateRecord(emp);
        emp.save();
    },

    onWindowBeforeRender: function(component, eOpts) {
        var me = this,
            form = me.down('form'),
            emp = me._emp;
        if (!emp) {
            emp = Ext.create(me.getNs()+'.model.EmployInfo');
        }
        form.loadRecord(emp);
    }

});