/*
 * File: app/view/Entrance.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('sion.demo.view.Entrance', {
    extend: 'Ext.window.Window',
    alias: 'widget.Entrance',

    requires: [
        'sion.demo.view.MyPanel',
        'Ext.panel.Panel'
    ],

    height: 800,
    width: 1425,
    layout: 'fit',
    iconCls: 's_icon_org_gear',
    title: '例子学习',
    maximizable: true,
    minimizable: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            listeners: {
                resize: {
                    fn: me.onWindowResize,
                    scope: me
                }
            },
            items: [
                {
                    xtype: 'mypanel'
                }
            ]
        });

        me.callParent(arguments);
    },

    onWindowResize: function(window, width, height, eOpts) {
        //panel大小随着window变化
        //var panel = window.down('Panel');
        //panel.setSize(width, height-35);
    }

});