/*
 * File: app/view/MainTabPanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('sion.demo.view.MainTabPanel', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.mytabpanel',

    requires: [
        'Ext.panel.Panel',
        'Ext.tab.Tab',
        'Ext.Img',
        'Ext.form.FieldSet',
        'Ext.form.Label',
        'Ext.view.View',
        'Ext.XTemplate'
    ],

    itemId: 'MyTabPanel',
    activeTab: 0,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    iconCls: 's_icon_item_flag',
                    title: '首页',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'panel',
                            height: 350,
                            layout: 'fit',
                            items: [
                                {
                                    xtype: 'image',
                                    src: 'http://localhost:8080/sion-talent/recruit_background.png'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            height: 400,
                            hidden: true,
                            layout: {
                                type: 'hbox',
                                align: 'middle'
                            },
                            items: [
                                {
                                    xtype: 'panel',
                                    flex: 1,
                                    height: '100%',
                                    width: '33%',
                                    bodyStyle: 'background:#ffc; padding:10px;',
                                    title: '',
                                    layout: {
                                        type: 'table',
                                        columns: 3
                                    },
                                    items: [
                                        {
                                            xtype: 'fieldset',
                                            height: 300,
                                            width: 280,
                                            title: '求职者信息',
                                            layout: {
                                                type: 'table',
                                                columns: 3
                                            },
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    colspan: 3,
                                                    iconCls: 's_icon_action_copy',
                                                    text: '简历库',
                                                    listeners: {
                                                        click: {
                                                            fn: me.onButtonClick,
                                                            scope: me
                                                        }
                                                    }
                                                },
                                                {
                                                    xtype: 'label',
                                                    colspan: 3,
                                                    text: '1.筛选，查看或导出求职者简历信息。'
                                                },
                                                {
                                                    xtype: 'label',
                                                    colspan: 3,
                                                    text: '2.将合适的人才推荐给相关公司。'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    height: '100%',
                                    width: '33%',
                                    layout: 'table',
                                    bodyStyle: 'background:#DFFFDF; padding:10px;',
                                    title: '',
                                    items: [
                                        {
                                            xtype: 'fieldset',
                                            height: 300,
                                            width: 280,
                                            title: '企业信息',
                                            layout: {
                                                type: 'table',
                                                columns: 3
                                            },
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    colspan: 3,
                                                    width: 98,
                                                    iconCls: 's_icon_item_book',
                                                    text: '企业信息',
                                                    listeners: {
                                                        click: {
                                                            fn: me.onButtonClick1,
                                                            scope: me
                                                        }
                                                    }
                                                },
                                                {
                                                    xtype: 'label',
                                                    colspan: 3,
                                                    text: '1.筛选和查看企业详细信息。'
                                                },
                                                {
                                                    xtype: 'label',
                                                    colspan: 3,
                                                    text: '2.将普通企业推荐为重点企业。'
                                                },
                                                {
                                                    xtype: 'button',
                                                    colspan: 3,
                                                    width: 98,
                                                    iconCls: 's_icon_file_star',
                                                    text: '重点企业',
                                                    listeners: {
                                                        click: {
                                                            fn: me.onButtonClick2,
                                                            scope: me
                                                        }
                                                    }
                                                },
                                                {
                                                    xtype: 'label',
                                                    colspan: 3,
                                                    text: '1.筛选和查看重点企业详细信息。'
                                                },
                                                {
                                                    xtype: 'label',
                                                    colspan: 3,
                                                    text: '2.取消重点企业的推荐。'
                                                },
                                                {
                                                    xtype: 'button',
                                                    colspan: 3,
                                                    iconCls: 's_icon_file_edit',
                                                    text: '未审批企业',
                                                    listeners: {
                                                        click: {
                                                            fn: me.onButtonClick3,
                                                            scope: me
                                                        }
                                                    }
                                                },
                                                {
                                                    xtype: 'label',
                                                    colspan: 3,
                                                    text: '1.查看和审批企业的注册信息。'
                                                },
                                                {
                                                    xtype: 'label',
                                                    colspan: 3,
                                                    text: '2.将未审批的注册企业信息批量Excel导出。'
                                                },
                                                {
                                                    xtype: 'button',
                                                    colspan: 3,
                                                    iconCls: 's_icon_file_error',
                                                    text: '未通过企业',
                                                    listeners: {
                                                        click: {
                                                            fn: me.onButtonClick4,
                                                            scope: me
                                                        }
                                                    }
                                                },
                                                {
                                                    xtype: 'label',
                                                    colspan: 3,
                                                    text: '1.查看未通过审批的企业信息。'
                                                },
                                                {
                                                    xtype: 'label',
                                                    colspan: 3,
                                                    text: '2.再次审批未通的企业。'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    height: '100%',
                                    width: '33%',
                                    layout: 'table',
                                    bodyStyle: 'background:#ACD6FF; padding:10px;',
                                    title: '',
                                    items: [
                                        me.processMyView({
                                            xtype: 'dataview',
                                            itemSelector: 'div',
                                            itemTpl: [
                                                'Data View Item {string}'
                                            ]
                                        })
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    processMyView: function(config) {
        return config;
    },

    onButtonClick: function(button, e, eOpts) {
         var tabs = Ext.ComponentQuery.query('#MyTabPanel')[0];
         var P1 = Ext.ComponentQuery.query('#ResumeInfoGrid')[0];
            if(!P1){
               P1 = Ext.create('sion.social.recruit.view.ResumeInfoGrid');
               P1.iconCls = button.iconCls;
               P1.title= button.text;
               P1.closable = true;
               tabs.add(P1);
            }
            tabs.setActiveTab(P1);
    },

    onButtonClick1: function(button, e, eOpts) {
                 var tabs = Ext.ComponentQuery.query('#MyTabPanel')[0];
                 var P1 = Ext.ComponentQuery.query('#ComInfo')[0];
                    if(!P1){
                       P1 = Ext.create('sion.social.recruit.view.ComInfo');
                       P1.iconCls = button.iconCls;
                       P1.title= button.text;
                       P1.closable = true;
                       tabs.add(P1);
                    }
                    tabs.setActiveTab(P1);
    },

    onButtonClick2: function(button, e, eOpts) {
                         var tabs = Ext.ComponentQuery.query('#MyTabPanel')[0];
                         var P1 = Ext.ComponentQuery.query('#PointCom')[0];
                            if(!P1){
                               P1 = Ext.create('sion.social.recruit.view.PointCom');
                               P1.iconCls = button.iconCls;
                               P1.title= button.text;
                               P1.closable = true;
                               tabs.add(P1);
                            }
                            tabs.setActiveTab(P1);
    },

    onButtonClick3: function(button, e, eOpts) {
                 var tabs = Ext.ComponentQuery.query('#MyTabPanel')[0];
                 var P1 = Ext.ComponentQuery.query('#ComWait')[0];
                    if(!P1){
                       P1 = Ext.create('sion.social.recruit.view.ComWait');
                       P1.iconCls = button.iconCls;
                       P1.title= button.text;
                       P1.closable = true;
                       tabs.add(P1);
                    }
                    tabs.setActiveTab(P1);
    },

    onButtonClick4: function(button, e, eOpts) {
         var tabs = Ext.ComponentQuery.query('#MyTabPanel')[0];
                 var P1 = Ext.ComponentQuery.query('#ComNoPass')[0];
                    if(!P1){
                       P1 = Ext.create('sion.social.recruit.view.ComNoPass');
                       P1.iconCls = button.iconCls;
                       P1.title= button.text;
                       P1.closable = true;
                       tabs.add(P1);
                    }
                    tabs.setActiveTab(P1);
    },

    openPanelTab: function(viewName, iconClass, text) {
        var tabs = Ext.ComponentQuery.query('#MyTabPanel')[0];
                         var P1 = Ext.ComponentQuery.query('#'+viewName)[0];
                            if(!P1){
                               P1 = Ext.create(this.getNamespace()+'.view.'+viewName);
                               P1.iconCls = iconClass;
                               P1.title= text;
                               P1.closable = true;
                               tabs.add(P1);
                            }
                            tabs.setActiveTab(P1);
    }

});